document.addEventListener('DOMContentLoaded',()=>{
 const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});
 document.querySelectorAll('.reveal').forEach(x=>obs.observe(x));
 const cur=document.createElement('div');cur.className='cursor';document.body.appendChild(cur);window.addEventListener('pointermove',e=>{cur.style.left=e.clientX+'px';cur.style.top=e.clientY+'px'});
 document.querySelectorAll('a,.btn,.tour-card,.service-card,.doctor').forEach(el=>{el.addEventListener('mouseenter',()=>{cur.style.width='34px';cur.style.height='34px'});el.addEventListener('mouseleave',()=>{cur.style.width='12px';cur.style.height='12px'})});
 document.querySelectorAll('.magnetic').forEach(el=>el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.12}px,${(e.clientY-r.top-r.height/2)*.12}px)`}));
 document.querySelectorAll('.magnetic').forEach(el=>el.addEventListener('pointerleave',()=>el.style.transform=''));
 const modal=document.querySelector('#filmModal'); const frames=[...document.querySelectorAll('.film-frame')]; let timer;
 function openFilm(){if(!modal)return;modal.classList.add('is-open');modal.setAttribute('aria-hidden','false');let i=0;frames.forEach((f,n)=>f.classList.toggle('is-active',n===0));const bar=modal.querySelector('.film-progress i');const go=()=>{i=(i+1)%frames.length;frames.forEach((f,n)=>f.classList.toggle('is-active',n===i));if(bar){bar.style.transition='none';bar.style.width=((i+1)/frames.length*100)+'%';requestAnimationFrame(()=>{bar.style.transition='width 6s linear';bar.style.width=(((i+2)%frames.length||frames.length)/frames.length*100)+'%'});}};timer=setInterval(go,6000)}
 function closeFilm(){modal?.classList.remove('is-open');modal?.setAttribute('aria-hidden','true');clearInterval(timer)}
 document.querySelectorAll('[data-film]').forEach(b=>b.addEventListener('click',openFilm));document.querySelectorAll('[data-film-close]').forEach(b=>b.addEventListener('click',closeFilm));document.addEventListener('keydown',e=>e.key==='Escape'&&closeFilm());
 document.querySelectorAll('form').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();const o=form.querySelector('output');if(o){o.textContent='Спасибо. В коммерческой версии эта форма будет отправлять заявку в CRM/Telegram.';o.style.display='block'}}));
});